#!/bin/sh

if [ $# -ne 3 ]; then
  echo "Usage: run-builds limp config install-root"
  exit 1
fi

limp=$1
config=$2
install=$3
progs="operator state statex heater-d heater-f localheat-d localheat-f"

echo '****************' doing $config
make clean
rm -f lib*.a
make CONFIG=$config LIMP=$limp
target=$install/$config-$limp/bin
[ -d $target ] || mkdir -p $target
for x in $progs ; do
  mv tests/$x $target/$x
done
