#!/bin/sh
./configure \
   --prefix=/Users/avp/Sandbox/USQCD/mdwf/install-new-1 \
   --target=cee-64 \
   --with-qmp=/Users/avp/Local/packages/current/qmp \
   --with-gsl=/Users/avp/Local/packages/current/gsl
