#!/bin/sh
USQCDDIST=/Users/avp/Local/packages/macosx-20130110
COPTS='-Wunused-but-set-variable -Wall -O3' \
./configure \
   --prefix=/Users/avp/Sandbox/USQCD/mdwf/install-working \
   --target=cee-64 \
   --with-qmp=$USQCDDIST/qmp \
   --with-gsl=$USQCDDIST/gsl
