/* This file allows second inclusion of qop-mdwf.h. It's a hack */
#undef QOP_MDWF_0bd50d0caeec4311a0d7c183032c43c2
#undef QOP_MDWF_DIM
#undef QOP_MDWF_FERMION_DIM
#undef QOP_MDWF_PROJECTED_FERMION_DIM
#undef QOP_MDWF_COLORS
#undef QOP_MDWF_DEFAULT_PRECISION
#undef QOP_MDWF_import_gauge
#undef QOP_MDWF_free_gauge
#undef QOP_MDWF_Gauge
#undef QOP_MDWF_import_fermion
#undef QOP_MDWF_export_fermion
#undef QOP_MDWF_allocate_fermion
#undef QOP_MDWF_free_fermion
#undef QOP_MDWF_Fermion
#undef QOP_MDWF_import_half_fermion
#undef QOP_MDWF_export_half_fermion
#undef QOP_MDWF_allocate_half_fermion
#undef QOP_MDWF_free_half_fermion
#undef QOP_MDWF_HalfFermion
#undef QOP_MDWF_DDW_operator
#undef QOP_MDWF_DDW_operator_conjugated
#undef QOP_MDWF_M_operator
#undef QOP_MDWF_M_operator_conjugated
#undef QOP_MDWF_DDW_CG
#undef QOP_MDWF_MxM_CG
#undef QOP_MDWF_MxM_SCG
#undef QOP_MDWF_madd_fermion
#undef QOP_MDWF_madd_half_fermion
#undef QOP_MDWF_dot_fermion
#undef QOP_MDWF_dot_half_fermion
#undef QOP_MDWF_norm2_fermion
#undef QOP_MDWF_norm2_half_fermion
