#!/bin/sh

if [ $# -ne 3 ]; then
  echo "Usage: run-builds limp config install-root"
  exit 1
fi

limp=$1
config=$2
install=$3

echo '****************' doing $config
make clean
rm -f lib*.a
make CONFIG=$config LIMP=$limp
target=$install/$config-$limp
[ -d $target ] || mkdir -p $target
for x in operator heater-d heater-f state statex ; do
  mv tests/$x $target/$x
done
